version: '3.7'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: capitals-quiz-backend
        ports:
            - "8000:80"
        volumes:
            - ./backend:/app/backend
        depends_on:
            - db
            - db-test
        networks:
            - app

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: capitals-quiz-frontend
        ports:
            - 5173:5173
        volumes:
            - ./frontend:/app/frontend
            - /app/frontend/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - backend
        networks:
            - app

    # Main MySQL Database (Development)
    db:
        image: mysql:8.0.37
        container_name: capitals-quiz-db
        env_file: ./backend/.env
        ports:
            - "3337:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "capitals-quiz"
            MYSQL_USER: "laravel"
            MYSQL_PASSWORD: "password"
        volumes:
            - db_data:/var/lib/mysql
            - ./backend/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app

    # MySQL Test Database
    db-test:
        image: mysql:8.0.37
        container_name: capitals-quiz-test-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "test_password"
            MYSQL_DATABASE: "capitals-quiz-test"
            MYSQL_USER: "test_laravel"
            MYSQL_PASSWORD: "test_password"
        ports:
            - "3338:3306"  # Avoid conflict with main MySQL
        volumes:
            - db_test_data:/var/lib/mysql
            - ./backend/docker/mysql/init-test.sql:/docker-entrypoint-initdb.d/init-test.sql
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    db_data:
    db_test_data:
